// profile.styles.ts
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  bgContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
    paddingTop: 120,
  },
  avatarCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#252C37",
    borderWidth: 2,
    borderColor: "#252C37",
    marginBottom: 16,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    resizeMode: "cover",
  },
  username: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#252C37",
    marginBottom: 4,
  },
  userId: {
    fontSize: 14,
    color: "#888",
    marginBottom: 4,
  },
  logoutIcon: {
    position: "absolute",
    top: 60,
    right: 25,
    zIndex: 10,
  },
  editButton: {
    marginTop: 16,
    backgroundColor: "#F8C61E",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  editButtonText: {
    color: "#252C37",
    fontWeight: "bold",
    fontSize: 16,
  },
  balanceActionsContainer: {
    width: "90%",
    backgroundColor: "#252C37",
    borderRadius: 16,
    alignItems: "center",
    paddingVertical: 22,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: "#1a202c",
    shadowColor: "#323f52ff",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  balanceSectionInner: {
    alignItems: "center",
    marginBottom: 18,
  },
  actionsRowCustom: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  actionButtonYellow: {
    flex: 1,
    backgroundColor: "#F8C61E",
    marginHorizontal: 6,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    shadowColor: "#FdD700",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  actionButtonYellowText: {
    color: "#252C37",
    fontWeight: "bold",
    fontSize: 16,
  },
  balanceLabel: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
  },
  balanceValue: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
  },
  infoSection: {
    width: "90%",
    backgroundColor: "#f4f4f4",
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  infoItem: {
    fontSize: 16,
    color: "#252C37",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
  },
  saveButton: {
    backgroundColor: "#F8C61E",
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    alignItems: "center",
  },
  saveButtonText: {
    fontWeight: "bold",
    color: "#252C37",
  },
  cancelButton: {
    backgroundColor: "#ccc",
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
    alignItems: "center",
  },
  cancelButtonText: {
    fontWeight: "bold",
    color: "#252C37",
  },
  cameraModal: {
    flex: 1,
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
  },
  cameraControls: {
    position: "absolute",
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  controlButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: "#ffffff60",
    borderRadius: 8,
  },
  shotButton: {
    backgroundColor: "#F8C61E",
  },
  controlText: {
    fontWeight: "bold",
    color: "#252C37",
  },
});
